### ISSUE TITLE
Not working with Home Assistant 0.97

### ISSUE THREAD

**Issue by DCooper-nz** [stuartmaxwell/spotprice#2]
I just updated to Home Assistant 0.97 and the script is no longer working, is this due to HA updating to python 3.7?

**Comment by DCooper-nz** [comment]
Ignore that seemed to be an issue with the price or cookie file which was just coincidental with the update, deleting those files sorted it.

**Comment by stuartmaxwell** [comment]
Thanks for the update. I've actually stopped using the script since we switched to Flick's fixed pricing. Good to hear it's still working for you.
